- hosts: nfs-server
  roles:
    - role: nfs_server
      export_directory: /var/nfs_shared
      share_to: "{{ groups['zk'] }}"

- hosts: zk:kafka
  roles:
    - { role: java, when: accept_oracle_licence }

- hosts: zk
  roles:
    - role: nfs_client
      nfs_mount: /opt/nfs_mount
      nfs_server: shared-storage
      nfs_path: /var/nfs_shared
    - role: exhibitor
      exhibitor_shared_conf_dir: /opt/nfs_mount
    - zookeeper

- hosts: kafka
  roles:
    - kafka
