- hosts: all
  roles:
    - { role: java, when: accept_oracle_licence }

- hosts: zk
  roles:
    - zookeeper

- hosts: kafka
  vars:
  - kafka_status_install_path: /opt/kafka_status
  roles:
    - kafka

  tasks:
  - name: install ruby
    yum:
      name: "{{ item }}"
    with_items:
    - ruby
    - ruby-devel
    - "@Development tools"
    - rubygem-bundler

  - name: Install kafka_Status
    git:
      repo: https://github.com/AwaNoodle/kafka-status.git
      dest: "{{ kafka_status_install_path }}"
      accept_hostkey: true
      force: yes

  - name: Set Execute for Kafka_Status
    file:
      path: "{{ kafka_status_install_path }}/kafka_status.rb"
      mode: a+x

  - name: Set Permissions for Kafka_Status Gemfile.lock
    file:
      path: "{{ kafka_status_install_path }}/Gemfile.lock"
      mode: a+rw

  - name: Bundle
    bundler:
      gemfile: "{{ kafka_status_install_path }}/Gemfile"
    sudo: no

- hosts: kafka-manager
  become: true

  tasks:
  - name: Get Initial ZK Host
    set_fact:
      initial_zk_host: "{{ hostvars[groups['zk'][0]]['ansible_enp0s8']['ipv4']['address'] }}"

  - name: Add Docker-Py
    yum:
      name: python-docker-py

  - name: install Docker
    yum:
      name: https://yum.dockerproject.org/repo/main/centos/7/Packages/docker-engine-1.11.0-1.el7.centos.x86_64.rpm
      update_cache: true

  - name: Start Docker
    service:
      name: docker
      state: started

  - name: Add Kafka Manager
    docker:
      name: kafkamanager
      image: sheepkiller/kafka-manager
      stdin_open: true
      ports:
      - 9000:9000
      env:
        ZK_HOSTS: "{{ initial_zk_host }}:2181"
