- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True  #when firewalld is stopped
  tags: nfs_client

- name: install nfs utils
  action: yum pkg={{ item }} state=present
  with_items:
    - "nfs-utils"
    - "nfs-utils-lib"
  tags: nfs_client

- name: ensure {{ nfs_mount }} mount-to directory exists
  file:
    path: "{{ nfs_mount }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  tags: nfs_client

- name: Ensure nfs services are running
  action: service name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - "nfs-server"
  tags: nfs_client

- name: mount the directory
  mount: >
   name={{ nfs_mount }}
   src={{ nfs_server }}:{{ nfs_path }}
   fstype=nfs
   opts=rw,sync,bg
   state=mounted
  tags: nfs_client
