- name: create group
  group:
    name: zookeeper
    state: present
  tags: exhibitor

- name: create user
  user:
    name: zookeeper
    group: zookeeper
  tags: exhibitor

- name: copy exhibitor jar
  copy: >
    src=exhibitor-standalone-1.5.5.jar
    dest=/etc/exhibitor/exhibitor-standalone.jar
    owner=zookeeper group=zookeeper mode=0644
  notify: restart exhibitor
  tags: exhibitor

- name: copy systemd config
  template:
    src: exhibitor-systemd.j2
    dest: /etc/systemd/system/exhibitor.service
    owner: root
    group: root
    mode: 644
  notify: start exhibitor
  tags: exhibitor
